// src/swagger.ts
import swaggerAutogen from 'swagger-autogen'

const swagger = swaggerAutogen()

const doc = {
  info: {
    version: '0.0.1',
    title: 'Swagger',
    description: 'Autogenerated',
  },
  host: 'localhost:4001',
  basePath: '/',
}

const outputFile = './swagger/swagger-output.json'
// If your entry lives in src/, point to it explicitly:
const routes = ['./src/index.ts']

swagger(outputFile, routes, doc)
