const swaggerAutogen = require('swagger-autogen')()

const doc = {
  info: {
    version: '0.0.1',
    title: 'Swagger',
    description: 'Autogenerated',
  },
  host: 'localhost:4001',
  basePath: '/',
}

const outputFile = './swagger/swagger-output.json'
const routes = ['./index.ts']

swaggerAutogen(outputFile, routes, doc)
